image: circutor/docker_go:v1.19.1
variables:
  DOCKER_DRIVER: overlay2
  GIT_DEPTH: 1
default:
  tags:
    - docker_aws
    - dev

before_script:
  - echo "List files:" && ls -l
  - echo "User:" && whoami
  - echo "IDs:" && id
  - echo "Hostname:" && hostname
  - echo "Current directory:" && pwd
  - echo "Go version:" && go version


stages:
- test
- build

lint:
  stage: test
  script:
    - make lint

test:
  stage: test
  script:
    - make test
  coverage:  /total:.+\(statements\).+\d+.\d+%/

build:
  stage: build
  script:
    - make build
