run:
  tests: true
  timeout: 5m
linters-settings:
  funlen:
    lines: 85
linters:
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - contextcheck
    - cyclop
    - dogsled
    - durationcheck
    - errcheck
    - errname
    - exhaustive
    - exportloopref
    - funlen
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - gofmt
    - gofumpt
    - goheader
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - importas
    - ineffassign
    - ireturn
    - lll
    - makezero
    - misspell
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - nlreturn
    - noctx
    - nolintlint
    - paralleltest
    - prealloc
    - predeclared
    - promlinter
    - staticcheck
    - stylecheck
    - tenv
    - testpackage
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace
    - wsl
    - thelper
    - errorlint
    - gochecknoglobals
    - forbidigo
    - gci
    - tagliatelle
    - wrapcheck
    - revive
    - goerr113
    - dupl
  disable:
    - forcetypeassert
    - gomnd
    - depguard
issues:
  exclude-rules:
    - path: (.+)_test.go
      linters:
        - funlen
        - dupl